name: 'Project_Snow_DBT'
version: '1.0.0'

profile: 'Project_Snow_DBT'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  Project_Snow_DBT:
 
    staging: 
      +schema: STAGING
      +materialized: table
    
    marts:
      +schema: MART
      +materialized: table

    intermediate: 
      +schema: INTERMEDIATE 
      +materialized: table